In [1]:
import pandas as pd
import numpy as np

In [2]:
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [3]:
fund_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

In [4]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [5]:
fund_master.duplicated().sum()

0

In [6]:
fund_master.describe()

,amfi_code,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount
count,40.000000,40.000000,40.000000,40.0,40.000000
mean,120247.000000,1.237000,0.812500,500.0,1277.500000
std,14534.998667,0.386584,0.387091,0.0,1082.847031
min,100016.000000,0.550000,0.000000,500.0,100.000000
25%,118632.750000,0.787500,1.000000,500.0,1000.000000
50%,119551.500000,1.425000,1.000000,500.0,1000.000000
75%,120842.250000,1.540000,1.000000,500.0,1000.000000
max,149324.000000,1.640000,1.000000,500.0,5000.000000

In [7]:
from pathlib import Path

files = Path("../data/raw").glob("*.csv")

for file in files:
    print("\n" + "="*60)
    print(file.name)

    df = pd.read_csv(file)

    print("Shape:", df.shape)
    print("Missing Values:")
    print(df.isnull().sum().sum())

    print("Duplicates:")
    print(df.duplicated().sum())

============================================================
01_fund_master.csv
Shape: (40, 15)
Missing Values:
0
Duplicates:
0

============================================================
02_nav_history - 02_nav_history.csv
Shape: (46000, 3)
Missing Values:
0
Duplicates:
0

============================================================
03_aum_by_fund_house - 03_aum_by_fund_house.csv
Shape: (90, 5)
Missing Values:
0
Duplicates:
0

============================================================
04_monthly_sip_inflows - 04_monthly_sip_inflows.csv
Shape: (48, 6)
Missing Values:
12
Duplicates:
0

============================================================
05_category_inflows - 05_category_inflows.csv
Shape: (144, 3)
Missing Values:
0
Duplicates:
0

============================================================
06_industry_folio_count - 06_industry_folio_count.csv
Shape: (21, 6)
Missing Values:
0
Duplicates:
0

============================================================
07_scheme_performance - 07_scheme_performance.csv
Shape: (40, 19)
Missing Values:
0
Duplicates:
0

============================================================
08_investor_transactions - 08_investor_transactions.csv
Shape: (32778, 13)
Missing Values:
0
Duplicates:
0

============================================================
09_portfolio_holdings - 09_portfolio_holdings.csv
Shape: (322, 8)
Missing Values:
0
Duplicates:
0

============================================================
10_benchmark_indices - 10_benchmark_indices.csv
Shape: (8050, 3)
Missing Values:
0
Duplicates:
0